//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAndWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobapply
    {
        public string workername { get; set; }
        public string jobname { get; set; }
        public string jobtitle { get; set; }
        public int jobid { get; set; }
    }
}
