//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAndWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Jobpost
    {
        [Display(Name = "Job Title")]
        [Required]
        public string jobtitle { get; set; }
        [Display(Name = "Publisher")]
        [Required]
        public string publishby { get; set; }
        [Display(Name = "Description")]
        public string jobdesp { get; set; }
        [Display(Name = "Experience")]
        [Required]
        public string exp { get; set; }
        [Display(Name = "Technology")]
        [Required]
        public string tech { get; set; }
        [Display(Name = "Date")]
        public string date { get; set; }
    }
}
