//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAndWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modelEntities1 : DbContext
    {
        public modelEntities1()
            : base("name=modelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hirer> hirers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Jobpost> Jobposts { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Jobapply> Jobapplies { get; set; }
    }
}
