//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickAndWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Profile
    {
        [Display(Name = "First Name")]
        [Required(ErrorMessage ="Required")]
        public string firstname { get; set; }
        [Display(Name = "Last Name")]
        [Required]
        public string lastname { get; set; }
        [Display(Name = "Date Of Birth")]
        [Required]
        public string dob { get; set; }
        [Display(Name = "MailID")]
        [Required]
        public string mailid { get; set; }
        [Display(Name = "Phone")]
        [Required]
        public Nullable<int> phone { get; set; }
        [Display(Name = "Technologies")]
        [Required]
        public string technologies { get; set; }
        [Display(Name = "Experience")]
        [Required]
        public string experience { get; set; }
        [Display(Name = "Previous Company")]
        public string previouscompany { get; set; }
        [Display(Name = "Hobbies")]
        public string hobbies { get; set; }
        [Display(Name = "Acheivements")]
        public string Acheivements { get; set; }
    }
}
